Repository AY2122S1-CS2103-T14-4/tp, pull requests merged in 2021-11, with the labels that each got.

#177 Fix Todo tab bugs discovered in PED
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/todo/Todo.java
  src/main/resources/view/AdvyzeTheme.css
Labels: type.Bug

#174 Displaying upcoming Events on startups
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ShowPastEventsCommand.java
  src/main/java/seedu/address/logic/commands/ShowUpcomingEventsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/UniqueScheduleList.java
Labels: type.Story, priority.High

#185 Bugs and fixes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/FilterScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterScheduleCommandParser.java
  src/main/java/seedu/address/model/event/Schedule.java
  src/main/java/seedu/address/model/event/exceptions/InvalidScheduleInputException.java
  src/main/java/seedu/address/model/event/predicates/ScheduleContainsDatePredicate.java
Labels: type.Bug

#193 Refactor Logic and Model components and fix parser bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Enhancement

#194 Update all segments of DG except Design and Implementation
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: type.Documentation

#197 Add author tags to make code RepoSense-compatible
  docs/team/kslui99.md
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task

#198 Update sample data for all tabs
  docs/UserGuide.md
  docs/images/dashboard-tab-v1.4.png
  docs/images/filter-contacts-v1.4.png
  docs/images/filter-events-v1.4.png
  docs/images/helpMessage.png
  docs/team/kslui99.md
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/DoneTodoCommand.java
  src/main/java/seedu/address/logic/commands/EditTodoCommand.java
  src/main/java/seedu/address/logic/commands/FilterTodoCommand.java
  src/main/java/seedu/address/logic/commands/FindTodoCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Documentation, type.Enhancement

#199 Fix tutorial section of Developer Guide
  docs/SettingUp.md
Labels: type.Documentation

#200 DG updates
  docs/DeveloperGuide.md
  docs/images/StorageClassDiagram.png
  docs/team/rickyaandrew.md
Labels: type.Documentation

#201 Update docs
  docs/team/rickyaandrew.md
  src/main/java/seedu/address/storage/JsonAdaptedStatus.java
Labels: type.Documentation

#202 Edit dg model
  docs/.Gemfile.swp
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonModelClassDiagram.puml
  docs/diagrams/ScheduleTodoGoalModelClassDiagram.puml
  docs/diagrams/test.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonModelClassDiagram.png
  docs/images/ScheduleTodoGoalModelClassDiagram.png
  docs/team/mokdarren.md
Labels: type.Documentation

#210 UG Final Bug Fixing
  docs/UserGuide.md
Labels: type.Documentation

#213 Fix table rendering in UG for summary of commands for contacts and details tab
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#214 Attempt to fix table rendering again
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#215 Reorder user stories in DG according to priority
  docs/DeveloperGuide.md
Labels: type.Documentation

#216 Dg fixes -model
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonModelClassDiagram.puml
  docs/images/PersonModelClassDiagram.png
Labels: type.Documentation

#242 Dg final bug fixes
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/team/kslui99.md
Labels: type.Documentation
